# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5c82e0615b50142eeba73b701e937fac5affce6a54775d1fbab6873a632a364eb96f0863c7f63bf4bfb5cc10015029820b725076b6120edfe64513b86e18c06

test:
  secret_key_base: 041d424104e04631e4be32e2440ffdeb1ac086cd07afc4eb9dec027a15cb8ae9d8ae83153903cb7ffadc2ffb70a542adbb4a27b1244a03836028c5243cb87e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
